---
apiVersion: v1
kind: Namespace
metadata:
  name: win-test-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: win-webserver
  name: win-webserver
  namespace: win-test-workload
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: win-webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
      - name: win-webserver
        command:
        - powershell
        - -File
        - webserver.ps1
        image: quay.revoweb.com/nrevo/webserver
        imagePullPolicy: IfNotPresent
        securityContext:
          windowsOptions:
            runAsUserName: ContainerAdministrator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: windows
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: os
        value: Windows

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: win-webserver
  name: win-webserver
  namespace: win-test-workload
spec:
  clusterIP: 172.30.18.48
  clusterIPs:
  - 172.30.18.48
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: win-webserver
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: win-webserver
  name: win-webserver
  namespace: win-test-workload
spec:
  host: web-win-test-workload.apps.ocs.openshift.works
  port:
    targetPort: 80
  tls:
    termination: edge
  to:
    kind: Service
    name: win-webserver
    weight: 100
  wildcardPolicy: None
